### ISSUE TITLE
Implement Checkout

### ISSUE THREAD

**Issue by iNoles** [iNoles/magento-flutter#9]
- [ ] Shipping Address
- [ ] Billing Address
- [ ] Shipping Method
- [ ] May Apply Coupon (if necessary)
- [ ] Set Email on Cart (Guests Only)
- [ ] Payment Methods
- [ ] Place Order

**Comment by onlinebizsoft** [comment]
Since this is very different for each website so I recommend you to take user to the web version for checkout (by loading a web viewer in the app)

**Comment by iNoles** [comment]
> Since this is very different for each website so I recommend you to take user to the web version for checkout (by loading a web viewer in the app)

Is there a way to share session management from Graphql to web? I am guessing it is the only way to do logged-in customers.

**Comment by onlinebizsoft** [comment]
Yes, it is possible (without logging in)

**Comment by iNoles** [comment]
> Yes, it is possible (without logging in)

can you point me in the right direction?
